### ISSUE TITLE
main.45ffd3ab.js:1 Uncaught Error: unable to get client provider context: unable to create client context: 

### ISSUE THREAD

**Issue by mohamednoushad** [IBM/hyperledger-fabric-evm-demo#7]
When I try to use the demo , I am not able to update the option and it returns me the following error in browser console. 

Error in option passed to client: Unable to load identity: failed to get signing identity: find enrollment cert path failed: read directory failed: open crypto-config/peerOrganizations/org1.example.com/users/9ab9dd6465daf96f9c53abd1d21f5cd2bc0df4ee@org1.example.com/msp/signcerts: no such file or directory

**Comment by swetharepakula** [comment]
Hi @mohamednoushad,

What option did you try to update? 

The error looks like it is coming from the Fabric SDK about the config you used to run your fab3 instance. It seems like this `crypto-config/peerOrganizations/org1.example.com/users/9ab9dd6465daf96f9c53abd1d21f5cd2bc0df4ee@org1.example.com/msp/signcerts` file is not there.

What config did you use? And what is your fabric network setup?

Regards,
Swetha

**Comment by mohamednoushad** [comment]
Hi @swetharepakula 

I was trying out directly the online demo link and found this error in the console.

I havent tried to set it up manually.

**Comment by swetharepakula** [comment]
We are not running the live demo anymore. Please try to the demo locally.
